DROP TABLE IF EXISTS `#__com_sos_risposte` CASCADE;
DROP TABLE IF EXISTS `#__com_sos_circolari_allegati` CASCADE;
DROP TABLE IF EXISTS `#__com_sos_allegati` CASCADE;
DROP TABLE IF EXISTS `#__com_sos_gruppi_destinatari` CASCADE;
DROP TABLE IF EXISTS `#__com_sos_utenti_destinatari` CASCADE;
DROP TABLE IF EXISTS `#__com_sos_circolari_gruppi_esclusi` CASCADE;
DROP TABLE IF EXISTS `#__com_sos_circolari` CASCADE;
DROP TABLE IF EXISTS `#__com_sos_azioni_utente` CASCADE;
DROP TABLE IF EXISTS `#__com_sos_configuration` CASCADE;
